### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by HashmatShadab** [zhyblue424/TGA-ZSR#2]
Hi!

Any update on when the model checkpoints will be made available?

**Comment by zhyblue424** [comment]
Thank you for your interest! We encourage users to replicate our results by training their own models using the provided code and datasets. Currently, we do not have plans to release the model checkpoints publicly. If this changes, we will share updates here. We appreciate your understanding.

**Comment by HashmatShadab** [comment]
Thank you.
